### PR TITLE
(linux) add pkg_config for Jack

### PR DESCRIPTION
**Pull request by edovino**
building on linux gave linker-errors

### CODE REVIEW

**Comment by danomatika** [comment]
Is this something more related to what OF itself needs to build? There is nothing JACK-related in ofxMidi as far as I know...

**Comment by edovino** [comment]
I stumbled across the error while building the midiOutputExample
apparently RtMidi requires Jack (or at least uses it by default?).
``libs/rtmidi/RtMidi.cpp`` contains this bit of code
```
#if defined(__UNIX_JACK__)
  if ( api == UNIX_JACK )
    rtapi_ = new MidiInJack( clientName, queueSizeLimit );
#endif
```
Not sure where/why ``__UNIX_JACK__``  is set though....

**Comment by edovino** [comment]
ah, it's probably oF that sets ``__UNIX_JACK__``

**Comment by danomatika** [comment]
Well, in either case, it’s needed.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Pull request merged**
