### PR TITLE
explicit conversion : Just to get rid of warnings

### PR DESCRIPTION
**Pull request by dimitre**
not sure if its the best way

### CODE REVIEW

**Comment by danomatika** [comment]
What is the warning?

**Comment by dimitre** [comment]
Implicit conversion loses integer precision: 'unsigned long' to 'unsigned int'

**Comment by dimitre** [comment]
it can be supressed by 
#pragma GCC diagnostic ignored "-Wshorten-64-to-32"

**Comment by danomatika** [comment]
In general, suppression is a bad idea, better to fix the issue.

The issue is that the ticks member variable is an `unsigned long` while the functions work with `unsigned int`. I probably used the larger type to ensure there would be plenty of space for *very long* songs. However when I wrote the rest of the API, I changed to unsigned ints which now clips this upper limit, however.

Two approaches:
1. Change ticks to `unsigned int`. This will lower the max number of ticks which can be stored internally but wouldn't introduce warnings to existing projects.
2. Change the beat functions to use `unsigned long`. This would fix the clipping of the max number of beats, but could introduce warnings in people's projects.

**Comment by danomatika** [comment]
Thanks

**Pull request merged**
